"""Makefile-mode ORFS re-close adapter for loopback validation."""
from __future__ import annotations

import os
import re
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path


DEFAULT_FLOW_ROOT = Path(os.environ.get("ORFS_ROOT", "/path/to/OpenROAD-flow-scripts"))
_WORST_SLACK_RE = re.compile(
    r"\bworst\s+slack\s+([-+]?\d+\.?\d*(?:[eE][-+]?\d+)?)",
    re.IGNORECASE,
)
_WNS_RE = re.compile(
    r"(?:Worst\s+Negative\s+Slack\s+\(WNS\)\s*[^\d-]*|^wns\s+)"
    r"([-+]?\d+\.?\d*(?:[eE][-+]?\d+)?)",
    re.IGNORECASE | re.MULTILINE,
)


@dataclass
class StageResult:
    success: bool
    returncode: int
    command: list[str]
    elapsed_sec: float
    work_home: str
    config_mk: str
    finish_rpt: str
    stdout_log: str
    stderr_log: str


class ORFSRecloseAdapter:
    """Run ORFS from RTL through finish in an isolated WORK_HOME."""

    def __init__(self, *, flow_root: Path = DEFAULT_FLOW_ROOT, timeout_sec: int = 3600):
        self.flow_root = Path(flow_root)
        self.flow_dir = self.flow_root / "flow"
        self.timeout_sec = timeout_sec

    def run_full_flow(
        self,
        *,
        design: str,
        platform: str,
        variant: str,
        verilog_files: list[Path],
        sdc: Path,
        work_dir: Path,
        base_config: Path | None = None,
        config_overrides: dict | None = None,
    ) -> StageResult:
        work_dir = Path(work_dir)
        work_home = work_dir / "orfs_work"
        log_dir = work_dir / "logs"
        config_mk = work_dir / "config.mk"
        work_home.mkdir(parents=True, exist_ok=True)
        log_dir.mkdir(parents=True, exist_ok=True)

        self._write_config(
            config_mk=config_mk,
            design=design,
            platform=platform,
            variant=variant,
            verilog_files=verilog_files,
            sdc=sdc,
            base_config=base_config,
            config_overrides=config_overrides or {},
        )
        return self._run_with_makefile(
            design=design,
            platform=platform,
            variant=variant,
            work_home=work_home,
            config_mk=config_mk,
            log_dir=log_dir,
        )

    def _write_config(
        self,
        *,
        config_mk: Path,
        design: str,
        platform: str,
        variant: str,
        verilog_files: list[Path],
        sdc: Path,
        base_config: Path | None,
        config_overrides: dict,
    ) -> None:
        lines = ["# Auto-generated by microsurgeon_flow.orfs_reclose"]
        if base_config is not None:
            lines.append(f"include {Path(base_config).resolve()}")
        lines.extend([
            f"export DESIGN_NAME = {design}",
            f"export PLATFORM = {platform}",
            f"export FLOW_VARIANT = {variant}",
            "export VERILOG_FILES = " + " ".join(
                str(Path(p).resolve()) for p in verilog_files
            ),
            f"export SDC_FILE = {Path(sdc).resolve()}",
        ])
        for key, value in sorted(config_overrides.items()):
            lines.append(f"export {key} = {value}")
        config_mk.write_text("\n".join(lines) + "\n")

    def _run_with_makefile(
        self,
        *,
        design: str,
        platform: str,
        variant: str,
        work_home: Path,
        config_mk: Path,
        log_dir: Path,
    ) -> StageResult:
        cmd = [
            "make",
            "-C",
            str(self.flow_dir),
            f"DESIGN_CONFIG={config_mk}",
            f"WORK_HOME={work_home}",
            "all",
        ]
        env = os.environ.copy()
        env["FLOW_HOME"] = str(self.flow_dir)
        env["IN_NIX_SHELL"] = "1"

        stdout_log = log_dir / "orfs_reclose.stdout.log"
        stderr_log = log_dir / "orfs_reclose.stderr.log"
        start = time.time()
        try:
            proc = subprocess.run(
                cmd,
                cwd=str(self.flow_dir),
                env=env,
                text=True,
                capture_output=True,
                timeout=self.timeout_sec,
            )
            returncode = proc.returncode
            stdout = proc.stdout or ""
            stderr = proc.stderr or ""
        except subprocess.TimeoutExpired as exc:
            returncode = 124
            stdout = exc.stdout if isinstance(exc.stdout, str) else (
                exc.stdout or b""
            ).decode(errors="replace")
            stderr = exc.stderr if isinstance(exc.stderr, str) else (
                exc.stderr or b""
            ).decode(errors="replace")
        elapsed = time.time() - start
        stdout_log.write_text(stdout, errors="replace")
        stderr_log.write_text(stderr, errors="replace")

        finish_rpt = (
            work_home / "reports" / platform / design / variant / "6_finish.rpt"
        )
        return StageResult(
            success=(returncode == 0),
            returncode=returncode,
            command=cmd,
            elapsed_sec=elapsed,
            work_home=str(work_home),
            config_mk=str(config_mk),
            finish_rpt=str(finish_rpt),
            stdout_log=str(stdout_log),
            stderr_log=str(stderr_log),
        )


def parse_finish_worst_slack(report_path: Path) -> float | None:
    """Read STA worst slack from an ORFS finish report; no returncode shortcuts."""
    path = Path(report_path)
    if not path.is_file():
        return None
    text = path.read_text(errors="replace")
    match = _WORST_SLACK_RE.search(text)
    if match:
        return float(match.group(1))
    match = _WNS_RE.search(text)
    return float(match.group(1)) if match else None
